frontend:
  build: .
  links:
    - registry:path-to-your-registry-v2
  ports:
      # Serves the page via grunt
    - "9000:9000"
      # For live reload with grunt
    - "35729:35729"
  volumes:
    - ../:/source:rw
    - ./start-develop.sh:/root/start-develop.sh:ro
  environment:
    DOCKER_REGISTRY_SCHEME: "http"
    DOCKER_REGISTRY_HOST: "desktop.home.local"
    DOCKER_REGISTRY_PORT: 5000
registry:
  image: registry:2
  ports:
    - "5000:5000"
